#!/usr/bin/env bash
#Installs and configures HAproxy in a load balancer server

apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend abimbolamichael.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 280452-web-01 52.3.220.197:80
        server 280452-web-02 54.82.207.84:80
' >> /etc/haproxy/haproxy.cfg

service haproxy restart
