#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
hours=0
minutes=1
while ((hours <= 12))
do
	echo "Hour: $hours"
	((hours++))
	while ((minutes < 60))
	do
		echo $minutes
		((minutes++))
	done
	((minutes=1))
done
