#!/usr/bin/env bash
#Client configuration file

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
